const customClasses: Record<string, string> = {
  "brand-mark": "grid place-items-center rounded-[22px] bg-gradient-to-br from-emerald-700 to-emerald-500 text-white font-black tracking-tighter shadow-[0_16px_30px_rgba(4,120,87,.30)] h-16 w-16",
  small: "h-11 w-11 rounded-[17px] text-sm",
  eyebrow: "m-0 mb-2 text-xs font-black uppercase tracking-[0.14em] text-emerald-600",
  form: "mt-5 grid gap-3.5",
  "status-line": "mt-5 rounded-2xl bg-emerald-50 px-3.5 py-3 font-extrabold text-emerald-800",
  "toast-viewport": "fixed bottom-5 right-5 z-[120] grid w-[min(380px,calc(100vw-32px))] gap-2 print:hidden",
  "toast-card": "flex items-start justify-between gap-3 rounded-2xl border bg-white px-4 py-3 text-sm font-bold shadow-[0_18px_48px_rgba(15,23,42,.18)] [&_button]:grid [&_button]:h-7 [&_button]:w-7 [&_button]:place-items-center [&_button]:rounded-xl [&_button]:bg-slate-100 [&_button]:p-0 [&_button]:text-slate-500 [&_button]:shadow-none",

  "app-shell": "min-h-screen grid grid-cols-[292px_1fr] max-[860px]:block max-[1120px]:grid-cols-[96px_1fr] print:hidden",
  "app-shell-redesign": "min-h-screen bg-[#f8f9fb] max-[860px]:block",
  sidebar: "sticky top-0 flex h-screen flex-col gap-5 overflow-hidden px-4.5 py-5.5 text-white shadow-[22px_0_60px_rgba(15,23,42,.18)] max-[860px]:static max-[860px]:h-auto",
  "sidebar-redesign": "relative h-screen gap-5 bg-[linear-gradient(180deg,#0f2533_0%,#111827_58%,#101827_100%)] p-4 before:absolute before:inset-0 before:pointer-events-none before:bg-[radial-gradient(circle_at_0_0,rgba(16,185,129,.2),transparent_38%),radial-gradient(circle_at_100%_100%,rgba(20,184,166,.12),transparent_36%)] max-[860px]:static max-[860px]:h-auto",
  "brand-block": "relative grid items-center gap-3 text-white grid-cols-[auto_1fr] [&_strong]:block [&_strong]:text-lg [&_strong]:font-black [&_small]:mt-1 [&_small]:block [&_small]:text-xs [&_small]:font-semibold [&_small]:text-slate-400",
  "nav-redesign": "relative grid gap-2 overflow-y-auto pr-1 max-[860px]:grid-cols-3",
  "nav-item": "flex w-full items-center justify-start gap-3 rounded-2xl border border-transparent bg-transparent px-3.5 py-3 text-[13px] font-black text-slate-300 shadow-none hover:translate-y-0 hover:bg-white/10 hover:shadow-none max-[860px]:justify-center",
  active: "border-white/15 bg-gradient-to-br from-emerald-700 to-emerald-500 text-white shadow-[0_14px_28px_rgba(4,120,87,.26)]",
  selected: "border-emerald-400 bg-emerald-50 text-emerald-800",
  "nav-icon": "inline-grid h-5.5 w-5.5 flex-none place-items-center [&_svg]:block",
  "sidebar-bottom-redesign": "relative mt-auto grid gap-3",
  "support-row": "grid grid-cols-2 gap-2",
  "support-button": "flex items-center justify-center gap-1.5 rounded-2xl bg-white/5 px-2 py-2 text-xs font-black text-slate-300 shadow-none hover:translate-y-0 hover:bg-white/10 hover:shadow-none",
  support: "bg-teal-500/20 text-teal-200",
  "user-card-redesign": "grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 rounded-2xl border border-white/10 bg-white/5 p-3 text-white [&_strong]:block [&_strong]:truncate [&_strong]:text-sm [&_strong]:font-black [&_small]:block [&_small]:text-[11px] [&_small]:font-semibold [&_small]:text-slate-400",
  "user-avatar": "grid h-10 w-10 place-items-center rounded-2xl bg-emerald-500 text-sm font-black text-white",
  "logout-icon-button": "grid h-9 w-9 place-items-center rounded-xl border-0 bg-white/5 p-0 text-slate-300 shadow-none hover:translate-y-0 hover:bg-white/10 hover:shadow-none",
  "time-card-redesign": "flex items-center gap-3 rounded-2xl bg-white/5 p-3 text-slate-300 [&_strong]:block [&_strong]:text-xl [&_strong]:font-black [&_small]:block [&_small]:text-[11px] [&_small]:text-slate-400",
  "content-shell": "min-w-0",
  "content-shell-redesign": "min-w-0 bg-[#f8f9fb]",
  "status-strip-redesign": "sticky top-0 z-10 flex items-center justify-end gap-3 border-b border-slate-100 bg-[#f8f9fb]/90 px-8 py-3 backdrop-blur max-[860px]:static max-[860px]:justify-stretch [&_span]:rounded-full [&_span]:bg-emerald-50 [&_span]:px-3 [&_span]:py-1.5 [&_span]:text-xs [&_span]:font-bold [&_span]:text-emerald-700 [&_button]:rounded-xl [&_button]:bg-slate-900 [&_button]:px-3 [&_button]:py-2 [&_button]:text-xs [&_button]:text-white",
  "page-content": "mx-auto max-w-[1320px] p-7 max-[860px]:p-[18px]",
  "page-content-redesign": "relative mx-auto min-h-[calc(100vh-64px)] max-w-[1440px] p-7 max-[860px]:p-[18px]",
  "wizard-actions": "flex flex-wrap items-center justify-end gap-2.5",
  "modal-actions": "flex flex-wrap items-center justify-end gap-2.5 print:hidden",
  "page-help": "-mt-2 mb-4.5 flex flex-wrap items-center gap-2.5 rounded-[18px] border border-emerald-200 bg-gradient-to-r from-emerald-50 to-cyan-50 px-4 py-3 text-[13px] font-extrabold text-emerald-800 [&_span]:font-bold [&_span]:text-slate-700",
  "dashboard-grid": "mb-4 grid grid-cols-2 items-stretch gap-4 max-[980px]:grid-cols-1",
  "dashboard-bottom-grid": "mb-4 grid grid-cols-[minmax(0,1.15fr)_minmax(320px,.85fr)] items-start gap-4 max-[980px]:grid-cols-1",
  "dashboard-check-list": "grid gap-3 [&>div]:flex [&>div]:items-start [&>div]:gap-3 [&>div]:rounded-2xl [&>div]:border [&>div]:border-slate-100 [&>div]:bg-slate-50 [&>div]:p-3.5 [&_small]:mt-1 [&_small]:block [&_small]:text-slate-500",
  "field-label": "grid gap-2 text-[13px] font-black text-slate-600",
  "form-input": "w-full rounded-2xl border border-slate-200 bg-white px-3.5 py-3 text-[15px] text-slate-900 transition-all duration-150 focus:border-emerald-500 focus:outline-none focus:ring-4 focus:ring-emerald-500/15",
  "field-note": "-mt-0.5 block text-xs font-semibold leading-snug text-slate-500",
  hint: "mb-0 text-[13px] text-slate-500",
  "quick-launch-grid": "mb-4.5 grid grid-cols-4 gap-3.5 max-[980px]:grid-cols-2 max-[640px]:grid-cols-1",
  "compact-launch": "grid-cols-4 max-[980px]:grid-cols-2 max-[640px]:grid-cols-1",
  "launch-card": "grid min-h-[118px] content-center justify-items-start gap-2 rounded-2xl border border-slate-200 bg-white/95 text-left text-slate-900 shadow-[0_10px_30px_rgba(15,23,42,.06)] [&_span]:text-[13px] [&_span]:text-slate-500 [&_svg]:text-emerald-600",
  "product-form": "mb-5 grid grid-cols-2 gap-3 rounded-[20px] border border-slate-200 bg-slate-50 p-4 max-[640px]:grid-cols-1 [&_button]:col-span-full",
  "no-box": "border-0 bg-transparent p-0",
  "span-2": "col-span-full md:col-span-2",
  "span-all": "col-span-full",
  row: "flex items-center justify-between gap-3 border-b border-slate-100 py-3",
  "rich-row": "[&_small]:mt-1 [&_small]:block",
  "cart-row": "grid grid-cols-[1fr_86px_auto] items-center gap-3 border-b border-slate-100 py-3 max-[640px]:grid-cols-1 [&_input]:p-2.5 [&_input]:text-center [&_small]:mt-1 [&_small]:block [&_small]:text-slate-500",
  "total-row": "my-4.5 flex items-center justify-between gap-3 rounded-[18px] border border-emerald-200 bg-emerald-50 p-4 text-lg text-emerald-800",
  checkout: "w-full text-base",
  divider: "my-3 h-px bg-slate-200",
  "warning-row": "mx-0 my-1 rounded-2xl bg-amber-50 px-3",
  "amount-stack": "grid justify-items-end gap-1 text-right",
  positive: "text-emerald-600",
  negative: "text-red-600",
  "db-box": "grid gap-2 break-all rounded-[18px] border border-slate-200 bg-slate-50 p-4",
  "detail-panel": "grid gap-2.5",
  "stock-badge": "inline-flex items-center justify-center rounded-full bg-emerald-50 px-2.5 py-1.5 text-xs font-black text-emerald-700",
  "status-badge": "inline-flex items-center justify-center rounded-full bg-emerald-50 px-2.5 py-1.5 text-xs font-black text-emerald-700",
  "role-badge": "inline-flex items-center justify-center rounded-full bg-indigo-50 px-2.5 py-1.5 text-xs font-black uppercase text-indigo-700",
  "danger-stock": "bg-amber-50 text-amber-700",
  warning: "bg-amber-50 text-amber-700",
  "pos-product-grid": "grid gap-3 [grid-template-columns:repeat(auto-fill,minmax(190px,1fr))]",
  "electron-product-grid": "grid gap-3 [grid-template-columns:repeat(auto-fill,minmax(190px,1fr))]",
  "pos-product-card": "grid gap-3 rounded-[20px] border border-slate-200 bg-white p-3.5 shadow-[0_8px_20px_rgba(15,23,42,.04)] hover:border-emerald-300 hover:shadow-[0_14px_30px_rgba(4,120,87,.10)]",
  "electron-product-card": "min-h-[135px] cursor-pointer text-left shadow-[0_6px_18px_rgba(15,23,42,.04)] hover:-translate-y-0.5 hover:border-emerald-300 hover:shadow-[0_12px_26px_rgba(4,120,87,.10)] disabled:cursor-not-allowed disabled:opacity-50",
  "product-main": "grid min-w-0 gap-1 [&_strong]:truncate [&_small]:text-slate-500",
  "product-meta": "grid justify-items-end gap-1.5 text-right max-[980px]:justify-items-start max-[980px]:text-left",
  stepper: "-mt-1 mb-4.5 grid grid-cols-3 gap-2.5 max-[720px]:grid-cols-1",
  "agent-stepper": "grid-cols-4 max-[720px]:grid-cols-1",
  step: "flex items-center justify-start gap-2.5 rounded-2xl border border-slate-200 bg-white px-3.5 py-3 text-slate-700 shadow-sm [&_span]:inline-grid [&_span]:h-7 [&_span]:w-7 [&_span]:place-items-center [&_span]:rounded-full [&_span]:bg-emerald-50 [&_span]:text-emerald-600",
  "payment-choice-grid": "mb-3.5 grid grid-cols-3 gap-2.5 max-[720px]:grid-cols-1",
  "compact-payment-grid": "grid-cols-3 max-[640px]:grid-cols-1 [&_.choice-card]:min-h-[58px] [&_.choice-card]:justify-items-center [&_.choice-card]:text-center",
  "choice-card": "grid min-h-[88px] content-center gap-1.5 rounded-2xl border border-slate-200 bg-white px-4 py-3 text-left text-slate-900 shadow-none [&_span]:text-xs [&_span]:font-bold [&_span]:text-slate-500",
  "review-box": "my-3.5 grid gap-2.5 rounded-[20px] border border-slate-200 bg-slate-50 p-4 [&_div]:flex [&_div]:items-center [&_div]:justify-between [&_div]:gap-3 [&_div]:border-b [&_div]:border-slate-200 [&_div]:pb-2 [&_div:last-child]:border-b-0 [&_div:last-child]:pb-0 [&_span]:font-extrabold [&_span]:text-slate-500",
  "workflow-content": "grid gap-3.5",
  "modal-backdrop": "absolute inset-0 z-[80] grid min-h-[calc(100vh-64px)] place-items-center bg-slate-900/55 p-6 backdrop-blur print:bg-white print:p-0 print:backdrop-blur-none",
  "payment-modal": "max-h-[calc(100vh-48px)] w-[min(620px,100%)] overflow-auto rounded-[28px] bg-white p-5.5 shadow-[0_30px_90px_rgba(15,23,42,.35)]",
  "payment-total-box": "mb-4 rounded-3xl bg-gradient-to-br from-slate-900 to-emerald-900 p-5 text-white [&_span]:text-sm [&_span]:font-bold [&_span]:text-emerald-100 [&_strong]:block [&_strong]:text-4xl [&_strong]:font-black [&_small]:mt-1 [&_small]:block [&_small]:text-xs [&_small]:text-emerald-100/80",
  "payment-method-grid": "mb-4 grid grid-cols-3 gap-3 max-[560px]:grid-cols-1",
  "payment-method-card": "grid min-h-[96px] content-center justify-items-center gap-1.5 rounded-2xl border-2 border-slate-200 bg-white p-3 text-center text-slate-800 shadow-none hover:border-emerald-300 hover:bg-emerald-50 hover:translate-y-0 [&_svg]:text-emerald-600 [&_strong]:font-black [&_small]:rounded-full [&_small]:bg-slate-100 [&_small]:px-2 [&_small]:py-0.5 [&_small]:text-[10px] [&_small]:font-black [&_small]:text-slate-500",
  "payment-section": "grid gap-3 rounded-3xl border border-slate-200 bg-slate-50 p-4",
  "cash-shortcut-grid": "grid grid-cols-3 gap-2 max-[560px]:grid-cols-2",
  "change-box": "flex items-center justify-between gap-3 rounded-2xl border p-4 [&_span]:text-sm [&_span]:font-black [&_strong]:text-2xl [&_strong]:font-black",
  success: "border-emerald-200 bg-emerald-50 text-emerald-800",
  "payment-note-box": "flex items-center gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800 [&_svg]:flex-none",
  "shortcut-help": "my-4 flex items-center gap-2 rounded-2xl bg-slate-50 px-3.5 py-3 text-xs font-bold text-slate-500 [&_svg]:flex-none",
  "dialog-card": "max-h-[calc(100vh-48px)] w-[min(720px,100%)] overflow-auto rounded-[28px] bg-white p-5.5 shadow-[0_30px_90px_rgba(15,23,42,.35)]",
  "receipt-modal": "max-h-[calc(100vh-48px)] w-[min(520px,100%)] overflow-auto rounded-[28px] bg-white p-5.5 shadow-[0_30px_90px_rgba(15,23,42,.35)] print:max-h-none print:w-auto print:overflow-visible print:rounded-none print:p-0 print:shadow-none",
  "product-dialog": "w-[min(780px,100%)]",
  "dialog-form": "grid gap-3.5",
  "receipt-paper": "mx-auto grid w-[min(360px,100%)] gap-2.5 rounded-[18px] border border-dashed border-slate-300 bg-white p-5 font-mono text-slate-900 print:w-[80mm] print:rounded-none print:border-0 print:p-[10mm] print:shadow-none",
  "receipt-center": "grid justify-items-center gap-1 text-center [&_strong]:text-lg [&_span]:text-xs [&_span]:text-slate-500",
  "receipt-line": "my-1 border-t border-dashed border-slate-300",
  "receipt-meta": "flex items-start justify-between gap-3.5 [&_span]:text-xs [&_span]:text-slate-500",
  "receipt-item": "flex items-start justify-between gap-3.5 [&_div]:grid [&_div]:gap-1 [&_span]:text-xs [&_span]:text-slate-500",
  "receipt-total": "flex items-start justify-between gap-3.5 text-lg",
  "receipt-footer": "mt-2",
  "printer-panel": "mt-4 grid gap-2 rounded-3xl border border-slate-200 bg-slate-50 p-4",
  "printable-receipt": "print:block",
  "cart-list-scroll": "max-h-[48vh] overflow-auto pr-1",
  "pos-service-form": "mb-3 grid grid-cols-2 gap-3 rounded-3xl border border-emerald-100 bg-emerald-50/50 p-3 max-[640px]:grid-cols-1",
  "animate-fadeIn": "animate-[fadeIn_.18s_ease-out]",
  "compact-agent-stepper": "grid-cols-4 max-[720px]:grid-cols-1",
  "electron-cart-panel": "rounded-[28px]",
  "electron-pos-catalog": "rounded-[28px]",
  "history-electron-page": "grid gap-4",
  "history-stat-grid": "mb-0",
  "backup-list": "grid gap-2.5",
  "backup-row": "grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 rounded-[18px] border border-slate-200 bg-slate-50 p-3.5 max-[640px]:grid-cols-1 [&_div]:grid [&_div]:min-w-0 [&_div]:gap-1 [&_small]:truncate [&_small]:text-slate-500",
  "log-level": "inline-flex min-w-14 justify-center rounded-full bg-sky-100 px-2.5 py-1.5 text-[11px] font-black text-sky-700",
  warn: "bg-amber-50 text-amber-700",
  error: "bg-red-50 text-red-600",
  info: "bg-emerald-50 text-emerald-700",
  "pos-shell": "grid grid-cols-[minmax(0,1fr)_380px] items-start gap-5 max-[1120px]:grid-cols-1",
  "electron-pos-shell": "grid grid-cols-[minmax(0,1fr)_380px] items-start gap-5 max-[1120px]:grid-cols-1",
  "pos-catalog": "min-w-0",
  "pos-cart-panel": "sticky top-24 max-[1100px]:static",
  "pos-search-row": "mb-4 flex items-center gap-3 max-[720px]:grid max-[720px]:grid-cols-1",
  "pos-search-input": "flex min-w-0 flex-1 items-center gap-2 rounded-2xl border border-slate-200 bg-slate-50 px-3.5 py-0 text-slate-500 [&_svg]:flex-none [&_input]:border-0 [&_input]:bg-transparent [&_input]:px-0 [&_input]:shadow-none [&_input]:ring-0 [&_input]:focus:ring-0",
  "category-filter-row": "mb-3.5 flex flex-wrap gap-2",
  "electron-filter-row": "mb-3.5 flex flex-wrap gap-2",
  "filter-chip": "rounded-full border border-slate-200 bg-slate-50 px-3 py-2 text-[13px] text-slate-700 shadow-none hover:bg-slate-100",
  "electron-cart-row": "grid-cols-[minmax(0,1fr)_72px_auto] max-[640px]:grid-cols-1",
  "service-section-title": "my-[10px] text-xs font-black uppercase tracking-[0.12em] text-slate-500",
  "service-icon": "inline-grid h-[42px] w-[42px] place-items-center rounded-2xl bg-gradient-to-br from-emerald-700 to-teal-500 text-white",
  "login-shell": "grid min-h-screen grid-cols-[minmax(0,1.05fr)_minmax(420px,.95fr)] bg-[#f7faf9] max-[960px]:block",
  "login-brand-panel": "relative overflow-hidden bg-[linear-gradient(135deg,#0f172a_0%,#052e2b_55%,#111827_100%)] p-10 text-white before:absolute before:-right-32 before:-top-32 before:h-96 before:w-96 before:rounded-full before:bg-emerald-500/30 before:blur-3xl after:absolute after:-bottom-28 after:-left-24 after:h-80 after:w-80 after:rounded-full after:bg-teal-500/20 after:blur-3xl max-[960px]:hidden",
  "login-brand-content": "relative z-10 flex h-full flex-col justify-between gap-10",
  "login-logo-row": "flex items-center gap-4 [&_strong]:block [&_strong]:text-2xl [&_strong]:font-black [&_p]:m-0 [&_p]:text-sm [&_p]:font-semibold [&_p]:text-slate-400",
  "login-copy": "max-w-xl [&_h1]:text-[52px] [&_h1]:leading-[.95] [&_h1]:text-white [&_p]:text-base [&_p]:leading-relaxed [&_p]:text-slate-300 [&_.eyebrow]:text-emerald-200",
  "login-feature-list": "grid gap-3 [&_div]:flex [&_div]:items-center [&_div]:gap-3 [&_div]:text-sm [&_div]:font-bold [&_div]:text-slate-200 [&_svg]:text-emerald-400",
  "login-form-panel": "flex items-center justify-center bg-slate-50 p-6 lg:p-12",
  "login-mobile-brand": "mb-6 hidden items-center gap-3 max-[960px]:flex [&_strong]:block [&_strong]:text-xl [&_strong]:font-black [&_strong]:text-slate-900 [&_small]:block [&_small]:text-xs [&_small]:font-semibold [&_small]:text-slate-400",
  "login-card": "w-full max-w-md rounded-3xl border border-slate-200/70 bg-white p-8 shadow-[0_18px_54px_rgba(15,23,42,.12)]",
  "login-card-header": "mb-6 [&_h2]:mb-1 [&_h2]:text-2xl [&_h2]:font-black [&_h2]:text-slate-900 [&_p]:m-0 [&_p]:text-sm [&_p]:font-semibold [&_p]:text-slate-400",
  "login-form": "grid gap-4",
  "login-input-wrap": "relative flex items-center [&_svg]:absolute [&_svg]:left-4 [&_svg]:text-slate-400 [&_input]:w-full [&_input]:rounded-2xl [&_input]:border-2 [&_input]:border-slate-200 [&_input]:bg-slate-50/60 [&_input]:py-3.5 [&_input]:pl-12 [&_input]:pr-4 [&_input]:font-semibold [&_input]:focus:bg-white",
  "input-icon-button": "absolute right-2 grid h-9 w-9 place-items-center rounded-xl border-0 bg-transparent p-0 text-slate-400 shadow-none hover:translate-y-0 hover:bg-slate-100 hover:text-slate-600 hover:shadow-none",
  "login-submit": "mt-2 flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-br from-emerald-700 to-emerald-500 px-4 py-3.5 font-black text-white shadow-[0_12px_24px_rgba(4,120,87,.22)]",
  "electron-hero-card": "mb-4 grid min-h-[144px] content-center rounded-[24px] bg-[radial-gradient(circle_at_92%_10%,rgba(16,185,129,.35),transparent_20%),linear-gradient(135deg,#0f172a,#111827_55%,#0f4a43)] p-6 text-white [&>span]:text-sm [&>span]:font-bold [&>span]:text-slate-300 [&>strong]:text-[42px] [&>strong]:font-black [&>strong]:tracking-[-0.04em]",
  "hero-icon-box": "mb-3 grid h-9 w-9 place-items-center rounded-2xl bg-white/10 text-slate-200",
  "hero-chip-row": "mt-4 flex flex-wrap gap-2 [&_button]:rounded-full [&_button]:bg-white/10 [&_button]:px-3 [&_button]:py-2 [&_button]:text-xs [&_button]:font-black [&_button]:text-white [&_button]:shadow-none",
  "electron-stat-grid": "mb-4 grid grid-cols-4 gap-4 max-[1180px]:grid-cols-2 max-[720px]:grid-cols-1",
  "dashboard-simple-stats": "grid-cols-3 max-[980px]:grid-cols-1",
  "safe-banner": "mb-5 flex items-center gap-4 rounded-3xl border border-slate-200/80 bg-white p-4 shadow-[0_8px_22px_rgba(15,23,42,.05)] [&>span]:grid [&>span]:h-12 [&>span]:w-12 [&>span]:place-items-center [&>span]:rounded-2xl [&>span]:bg-emerald-50 [&>span]:text-xl [&>span]:font-black [&>span]:text-emerald-600 [&_strong]:text-emerald-700 [&_p]:m-0 [&_p]:text-sm [&_p]:text-emerald-700/80",
  "account-section-head": "mb-3 flex items-center justify-between text-sm font-black uppercase tracking-wide text-slate-600 [&_span]:text-xs [&_span]:text-slate-400",
  "account-card-row": "mb-5 grid grid-cols-4 gap-4 max-[1180px]:grid-cols-2 max-[720px]:grid-cols-1",
  "account-balance-card": "grid min-h-[126px] gap-1 rounded-3xl p-5 text-left text-white shadow-[0_14px_28px_rgba(15,23,42,.14)] hover:-translate-y-0.5 [&_span]:text-xs [&_span]:font-bold [&_span]:uppercase [&_span]:tracking-wide [&_span]:text-white/80 [&_strong]:text-lg [&_strong]:font-black [&_small]:text-white/70 [&_b]:text-2xl [&_b]:font-black",
  "account-green": "bg-gradient-to-br from-emerald-500 to-emerald-700",
  "account-blue": "bg-gradient-to-br from-cyan-700 to-sky-600",
  "account-navy": "bg-gradient-to-br from-slate-900 to-teal-700",
  "account-teal": "bg-gradient-to-br from-teal-400 to-teal-700",
  "electron-dashboard-grid": "mb-4 grid grid-cols-[minmax(0,1.5fr)_minmax(280px,.7fr)] gap-4 max-[980px]:grid-cols-1",
  "chart-card": "min-h-[320px]",
  "stock-card": "min-h-[320px]",
  "chart-summary-pill": "rounded-2xl bg-slate-50 px-4 py-2 text-right [&_span]:block [&_span]:text-[10px] [&_span]:font-black [&_span]:uppercase [&_span]:text-cyan-600 [&_strong]:text-sm [&_strong]:font-black [&_strong]:text-cyan-700",
  green: "[&_span]:text-emerald-500 [&_strong]:text-emerald-700",
  "electron-service-layout": "grid grid-cols-[minmax(280px,.95fr)_minmax(420px,1.25fr)_minmax(300px,.8fr)] items-start gap-[18px] max-[1180px]:grid-cols-1",
  "service-catalog-panel": "rounded-[28px]",
  "service-form-panel": "rounded-[28px]",
  "service-history-panel": "rounded-[28px]",
  "service-filter-row": "mb-4 flex flex-wrap gap-2 border-b border-slate-100 pb-3",
  "service-preset-row": "flex flex-wrap gap-2",
  "electron-service-grid": "grid grid-cols-2 gap-3 max-[640px]:grid-cols-1",
  "electron-service-card": "relative grid min-h-[150px] content-center justify-items-center gap-2 rounded-2xl border-2 border-transparent bg-white p-4 text-center text-slate-900 shadow-[0_8px_22px_rgba(15,23,42,.05)] hover:-translate-y-0.5 hover:border-teal-300 hover:bg-teal-50 hover:shadow-[0_14px_32px_rgba(20,184,166,.12)] [&_small]:text-xs [&_small]:font-bold [&_small]:text-slate-500 [&_em]:rounded-full [&_em]:bg-amber-100 [&_em]:px-2 [&_em]:py-1 [&_em]:text-[11px] [&_em]:font-black [&_em]:not-italic [&_em]:text-amber-700",
  "service-fav": "absolute right-2 top-2 text-amber-400",
  "service-progress-header": "mb-4 flex items-start justify-between gap-3 rounded-3xl bg-slate-50 p-4 [&_p]:m-0 [&_p]:text-sm [&_p]:text-slate-500 [&>span]:rounded-full [&>span]:bg-emerald-100 [&>span]:px-3 [&>span]:py-1 [&>span]:text-xs [&>span]:font-black [&>span]:text-emerald-700",
  "agent-summary-grid": "grid grid-cols-2 gap-3 max-[640px]:grid-cols-1 [&_div]:rounded-2xl [&_div]:border [&_div]:border-slate-200 [&_div]:bg-slate-50 [&_div]:p-4 [&_span]:block [&_span]:text-xs [&_span]:font-black [&_span]:uppercase [&_span]:tracking-wide [&_span]:text-slate-400 [&_strong]:text-lg [&_strong]:font-black [&_strong]:text-slate-950",
  "electron-review-box": "bg-slate-50",
  "history-filter-panel": "mb-4 grid gap-3 p-3",
  "electron-tabs": "flex flex-wrap gap-2",
  "electron-tab": "flex items-center gap-2 rounded-2xl bg-slate-50 px-4 py-3 text-sm font-black text-slate-600 shadow-none hover:translate-y-0 hover:bg-slate-100 hover:shadow-none",
  "status-filter-row": "flex flex-wrap gap-2 border-t border-slate-100 pt-3",
  "history-layout": "grid grid-cols-[minmax(0,1.25fr)_minmax(300px,.75fr)] items-start gap-4 max-[1080px]:grid-cols-1",
  "history-status-badge": "inline-flex items-center justify-center rounded-full px-2.5 py-1.5 text-xs font-black",
  completed: "bg-emerald-50 text-emerald-700",
  pending: "bg-amber-50 text-amber-700",
  void: "bg-red-50 text-red-600",
  reversed: "bg-red-50 text-red-600",
  "history-table-card": "min-w-0 rounded-[28px]",
  "transaction-detail-card": "rounded-[28px]",
  "master-tabs": "mb-4 flex flex-wrap gap-2 rounded-3xl border border-slate-200 bg-white p-2 shadow-[0_8px_22px_rgba(15,23,42,.05)]",
  "category-grid": "grid grid-cols-3 gap-3 max-[980px]:grid-cols-2 max-[640px]:grid-cols-1",
  "category-card": "flex items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-[0_6px_18px_rgba(15,23,42,.04)] [&_svg]:text-emerald-600 [&_strong]:block [&_strong]:font-black [&_strong]:text-slate-900 [&_small]:block [&_small]:text-slate-500",
  "cash-summary-grid": "mb-5 grid grid-cols-[minmax(260px,1.15fr)_repeat(3,minmax(0,.75fr))] gap-4 max-[1180px]:grid-cols-2 max-[720px]:grid-cols-1",
  "cash-total-card": "rounded-3xl bg-gradient-to-r from-emerald-500 to-teal-500 p-5 text-white shadow-[0_12px_30px_rgba(16,185,129,.25)] [&_span]:text-sm [&_span]:font-bold [&_span]:text-emerald-100 [&_strong]:block [&_strong]:text-3xl [&_strong]:font-black [&_small]:mt-1 [&_small]:block [&_small]:text-xs [&_small]:font-semibold [&_small]:text-emerald-100",
  "cash-summary-card": "flex items-center gap-3 rounded-3xl border border-slate-200 bg-white p-5 shadow-[0_8px_22px_rgba(15,23,42,.05)] [&_svg]:text-emerald-600 [&_span]:block [&_span]:text-xs [&_span]:font-black [&_span]:uppercase [&_span]:tracking-wide [&_span]:text-slate-400 [&_strong]:block [&_strong]:text-lg [&_strong]:font-black [&_strong]:text-slate-950",
  "cash-section-head": "mb-3 flex items-center justify-between [&_strong]:block [&_strong]:text-sm [&_strong]:font-black [&_strong]:uppercase [&_strong]:tracking-wide [&_strong]:text-slate-600 [&_span]:text-xs [&_span]:font-semibold [&_span]:text-slate-400 [&_small]:text-xs [&_small]:font-semibold [&_small]:text-slate-400",
  "cash-account-grid": "mb-5 grid grid-cols-4 gap-4 max-[1180px]:grid-cols-2 max-[720px]:grid-cols-1",
  "cash-account-card": "rounded-3xl p-5 text-white shadow-[0_14px_34px_rgba(15,23,42,.16)] [&_h2]:mb-3 [&_h2]:text-xl [&_h2]:font-black [&_small]:text-white/70 [&>strong]:block [&>strong]:text-2xl [&>strong]:font-black [&_p]:m-0 [&_p]:text-xs [&_p]:text-white/70",
  "cash-account-top": "mb-5 flex items-center justify-between [&_span]:text-xs [&_span]:font-black [&_span]:uppercase [&_span]:tracking-wide [&_span]:text-white/70",
  "cash-account-actions": "mt-4 grid grid-cols-2 gap-2 [&_button]:rounded-xl [&_button]:bg-white/15 [&_button]:px-2 [&_button]:py-2 [&_button]:text-xs [&_button]:font-black [&_button]:text-white [&_button]:shadow-none [&_button:hover]:translate-y-0 [&_button:hover]:bg-white/25 [&_button:hover]:shadow-none",
  "cash-account-green": "bg-gradient-to-br from-emerald-500 to-emerald-700",
  "cash-account-blue": "bg-gradient-to-br from-cyan-700 to-sky-600",
  "cash-account-navy": "bg-gradient-to-br from-slate-900 to-teal-700",
  "cash-account-emerald": "bg-gradient-to-br from-teal-400 to-teal-700",
  "cash-account-teal": "bg-gradient-to-br from-teal-700 to-teal-400",
  "cash-layout-grid": "grid grid-cols-[minmax(0,1.35fr)_minmax(300px,.65fr)] items-start gap-4 max-[1080px]:grid-cols-1",
  "cash-mutation-card": "rounded-[28px]",
  "cash-side-panel": "rounded-[28px]",
  "statement-page": "grid gap-4",
  "statement-filter-card": "grid gap-4 p-4",
  "statement-filter-label": "mb-2 block text-[13px] font-black text-slate-600",
  "statement-preset-row": "flex flex-wrap gap-2",
  "statement-stat-grid": "mb-0",
  "statement-layout": "grid grid-cols-[minmax(0,1.35fr)_minmax(300px,.65fr)] items-start gap-4 max-[1080px]:grid-cols-1",
  "statement-table-card": "min-w-0 rounded-[28px]",
  "statement-side-card": "rounded-[28px]",
  "debt-page": "grid gap-4",
  "debt-stat-grid": "mb-0",
  "debt-filter-panel": "p-3",
  "debt-layout": "grid grid-cols-[minmax(0,1.35fr)_minmax(360px,.8fr)] items-start gap-[18px] max-[1080px]:grid-cols-1",
  "debt-list-card": "rounded-[28px]",
  "debt-form-stack": "grid gap-4 xl:sticky xl:top-24 [&>div]:rounded-[28px]",
  "debt-actions": "flex flex-wrap gap-2 lg:justify-end [&_button]:px-3 [&_button]:py-2 [&_button]:text-xs",
  "logs-page": "grid gap-4",
  "logs-stat-grid": "mb-0",
  "logs-filter-card": "grid gap-3 p-3",
  "logs-layout": "grid grid-cols-[minmax(0,1.3fr)_minmax(300px,.7fr)] items-start gap-4 max-[1080px]:grid-cols-1",
  "logs-table-card": "min-w-0 rounded-[28px]",
  "logs-side-card": "rounded-[28px]",
  "reports-page": "grid gap-4",
  "reports-stat-grid": "mb-0",
  "reports-layout": "grid grid-cols-[minmax(0,1.25fr)_minmax(320px,.75fr)] items-start gap-4 max-[1080px]:grid-cols-1",
  "reports-chart-card": "rounded-[28px]",
  "reports-side-card": "rounded-[28px]",
  "reports-note-card": "rounded-[28px]",
  "settings-page": "grid gap-4",
  "settings-grid": "grid grid-cols-2 gap-4 max-[920px]:grid-cols-1",
  "settings-card": "relative overflow-hidden rounded-[28px]",
  "settings-card-icon": "mb-4 grid h-12 w-12 place-items-center rounded-2xl bg-emerald-50 text-emerald-600",
  blue: "bg-cyan-50 text-cyan-700",
  amber: "bg-amber-50 text-amber-600",
  teal: "bg-teal-50 text-teal-700",
  "settings-user-form": "grid-cols-2 max-[640px]:grid-cols-1",
  "settings-user-list": "grid gap-2.5",
  "settings-action-grid": "grid grid-cols-2 gap-2 max-[640px]:grid-cols-1",
  "settings-info-grid": "grid gap-2.5 [&_div]:flex [&_div]:items-center [&_div]:gap-3 [&_div]:rounded-2xl [&_div]:border [&_div]:border-slate-200 [&_div]:bg-slate-50 [&_div]:p-4 [&_div]:text-sm [&_div]:font-semibold [&_div]:text-slate-600 [&_svg]:flex-none [&_svg]:text-emerald-600",
};

export function tw(value: string | false | null | undefined) {
  if (!value) return undefined;
  return value
    .split(/\s+/)
    .filter(Boolean)
    .flatMap((token) => (customClasses[token] ?? token).split(/\s+/).filter(Boolean))
    .join(" ");
}
