"use client";

import type { LucideProps, LucideIcon } from "lucide-react";
import {
  AlertCircle,
  AlertTriangle,
  AlarmClock,
  Archive,
  ArrowUpRight,
  Banknote,
  BarChart3,
  Bell,
  BellOff,
  Bookmark,
  Briefcase,
  Building2,
  Calculator,
  Calendar,
  Camera,
  CheckCircle2,
  Check,
  Circle,
  ClipboardList,
  Cookie,
  CreditCard,
  CupSoda,
  Database,
  Dice5,
  DollarSign,
  Download,
  Droplet,
  Eye,
  Film,
  FileText,
  Folder,
  FolderOpen,
  Gamepad,
  Gamepad2,
  Gift,
  Globe,
  Hammer,
  Hand,
  Hash,
  Heart,
  HeartPulse,
  HelpCircle,
  Home,
  Image as ImageIcon,
  Inbox,
  Info,
  Infinity as InfinityIcon,
  Key,
  KeyRound,
  Landmark,
  Lightbulb,
  Link,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  Milk,
  Minus,
  NotebookPen,
  Package,
  Palette,
  Paperclip,
  Pencil,
  Phone,
  PiggyBank,
  Pill,
  Pin,
  Plus,
  Puzzle,
  Radio,
  Receipt,
  ReceiptText,
  RefreshCw,
  Rocket,
  Ruler,
  Save,
  Scissors,
  ScrollText,
  Send,
  Settings,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Signal,
  Smartphone,
  Snowflake,
  Spade,
  Sparkles,
  Square,
  Stamp,
  Star,
  Store,
  Tag,
  Target,
  Theater,
  Timer,
  TrendingDown,
  TrendingUp,
  Trash2,
  Tv,
  Type,
  Unlock,
  Upload,
  Usb,
  User,
  Video,
  Wallet,
  Wheat,
  Wrench,
  XCircle,
  Zap,
} from "lucide-react";

// Map string name → Lucide icon component
const ICON_MAP: Record<string, LucideIcon> = {
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "alarm-clock": AlarmClock,
  archive: Archive,
  "arrow-up-right": ArrowUpRight,
  banknote: Banknote,
  "bar-chart-3": BarChart3,
  bell: Bell,
  "bell-off": BellOff,
  bookmark: Bookmark,
  briefcase: Briefcase,
  building: Building2,
  "building-2": Building2,
  calculator: Calculator,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  "check-circle": CheckCircle2,
  "check-circle-2": CheckCircle2,
  circle: Circle,
  "clipboard-list": ClipboardList,
  cookie: Cookie,
  "credit-card": CreditCard,
  "cup-soda": CupSoda,
  database: Database,
  dice: Dice5,
  "dollar-sign": DollarSign,
  download: Download,
  droplet: Droplet,
  eye: Eye,
  film: Film,
  "file-text": FileText,
  folder: Folder,
  "folder-open": FolderOpen,
  gamepad: Gamepad,
  "gamepad-2": Gamepad2,
  gift: Gift,
  globe: Globe,
  hammer: Hammer,
  hand: Hand,
  hash: Hash,
  heart: Heart,
  "heart-pulse": HeartPulse,
  "help-circle": HelpCircle,
  home: Home,
  image: ImageIcon,
  inbox: Inbox,
  info: Info,
  infinity: InfinityIcon,
  key: Key,
  "key-round": KeyRound,
  landmark: Landmark,
  lightbulb: Lightbulb,
  link: Link,
  lock: Lock,
  mail: Mail,
  "map-pin": MapPin,
  megaphone: Megaphone,
  milk: Milk,
  minus: Minus,
  "notebook-pen": NotebookPen,
  package: Package,
  palette: Palette,
  paperclip: Paperclip,
  pencil: Pencil,
  phone: Phone,
  "piggy-bank": PiggyBank,
  pill: Pill,
  pin: Pin,
  plus: Plus,
  puzzle: Puzzle,
  radio: Radio,
  receipt: Receipt,
  "receipt-text": ReceiptText,
  "refresh-cw": RefreshCw,
  rocket: Rocket,
  ruler: Ruler,
  save: Save,
  scissors: Scissors,
  "scroll-text": ScrollText,
  send: Send,
  settings: Settings,
  shirt: Shirt,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  signal: Signal,
  smartphone: Smartphone,
  smoke: Sparkles, // Lucide doesn't have smoke icon, use sparkles as fallback
  snowflake: Snowflake,
  spade: Spade,
  sparkles: Sparkles,
  square: Square,
  stamp: Stamp,
  star: Star,
  store: Store,
  tag: Tag,
  target: Target,
  theater: Theater,
  timer: Timer,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  "trash-2": Trash2,
  tv: Tv,
  type: Type,
  unlock: Unlock,
  upload: Upload,
  usb: Usb,
  user: User,
  video: Video,
  wallet: Wallet,
  wheat: Wheat,
  wrench: Wrench,
  "x-circle": XCircle,
  zap: Zap,
  // Semantic aliases
  bank: Landmark,
  cash: Banknote,
  money: Banknote,
  "party-popper": Sparkles, // Lucide doesn't have PartyPopper, use Sparkles
};

export interface DynamicIconProps extends Omit<LucideProps, "ref" | "name"> {
  name: string | null | undefined;
  fallback?: string;
}

/**
 * Render Lucide icon dari string name.
 *
 * Pemakaian:
 *   <DynamicIcon name="package" size={20} className="text-blue-500" />
 *   <DynamicIcon name={category.icon} fallback="package" />
 *
 * Jika name tidak dikenal, gunakan fallback (default: "package").
 */
export function DynamicIcon({
  name,
  fallback = "package",
  ...props
}: DynamicIconProps) {
  const iconName = name && ICON_MAP[name] ? name : fallback;
  const Icon = ICON_MAP[iconName] || Package;
  return <Icon {...props} />;
}

/**
 * Daftar nama icon yang tersedia, untuk dipakai di icon picker.
 */
export const AVAILABLE_ICONS = Object.keys(ICON_MAP).sort();

export default DynamicIcon;
